version: '3.4'

services:
  meetplanning-db:
    image: mcr.microsoft.com/mssql/server:2022-latest 
    environment:
      SA_PASSWORD: "sqlserver!Password"
      ACCEPT_EULA: "Y"
    ports:
      - 1434:1433 # exposed just for debugging purposes

  meetplanning.api:
    image: ${DOCKER_REGISTRY-}meetplanningapi
    build:
      context: .
      dockerfile: src/Services/MeetPlanning/MeetPlanning.API/Dockerfile
    depends_on:
        - meetplanning-db

  teammanagement.api:
    image: ${DOCKER_REGISTRY-}teammanagementapi
    build:
      context: .
      dockerfile: src/Services/TeamManagement/TeamManagement.API/Dockerfile

