version: '3.4'

services:
  meetplanning-db:
    image: mcr.microsoft.com/mssql/server:2022-latest 
    environment:
      SA_PASSWORD: "sqlserver!Password"
      ACCEPT_EULA: "Y"
    ports:
      - 1434:1433 # exposed just for debugging purposes


  meetplanning.api:
    image: ${DOCKER_REGISTRY-}meetplanningapi
    build:
      context: .
      dockerfile: src/Services/MeetPlanning/MeetPlanning.API/Dockerfile
    depends_on:
        - meetplanning-db
    ports:
      - 55382:8080  # exposed just for debugging


  eventstore.db:
    image: eventstore/eventstore:24.2.0-jammy
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "2113:2113"     # exposed for debugging
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

  teammanagement.api:
    image: ${DOCKER_REGISTRY-}teammanagementapi
    build:
      context: .
      dockerfile: src/Services/TeamManagement/TeamManagement.API/Dockerfile
    ports:
      - 55378:8080  # exposed just for debugging
    depends_on:
        - eventstore.db


  reactspa:
    image: ${DOCKER_REGISTRY-}reactspa
    build:
      context: src/WebApp/ReactSPA
      dockerfile: Dockerfile
    ports:
        - 5173:5173
    environment:
      - APIGATEWAY_HTTP_URL=ocelotgw:8080



  ocelotgw:
    image: ${DOCKER_REGISTRY-}ocelotgw
    build:
      context: .
      dockerfile: src/APIGateway/OcelotGw/Dockerfile
    ports:
        - 53534:8080
        - 53535:8081


volumes:
  eventstore-volume-data:
  eventstore-volume-logs:



